[tool.poetry]
name = "whodunit-stylometry"
version = "0.1.0"
description = "Modelado estilístico de la novela de misterio - Un análisis computacional de autores canónicos"
readme = "README.md"
authors = ["Teresa García Ceva <tgarciace@uoc.edu>"]
packages = [{ include = "whodunit_stylometry", from = "src" }]


[tool.poetry.dependencies]
python = ">=3.11,<3.15"

pandas = ">=3,<4"
numpy = ">=2.4,<3"
matplotlib = ">=3.10,<4"
seaborn = ">=0.13,<0.14"
spacy = ">=3.8,<4"
nltk = ">=3.9,<4"
scipy = ">=1.17,<2"
unidecode = "^1.4.0"


[tool.poetry.group.dev.dependencies]
pytest = ">=9,<10"
ruff = ">=0.15,<0.16"
black = ">=26.1,<27"
pre-commit = ">=4.5,<5"
ipykernel = ">=7.1,<8"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.black]
line-length = 120
target-version = ["py311"]


[tool.ruff]
line-length = 120
target-version = "py311"
